### ISSUE TITLE
PluginManager issue 

### ISSUE THREAD

**Issue by yalem-a** [Rbillon59/jmeter-k8s-starterkit#33]
The script returns the following error as it tries to execute ''echo "sh PluginsManagerCMD.sh install-for-jmx ${jmx} > plugins-install.out 2> plugins-install.err". 

Have you encountered this?

ERROR: java.lang.InternalError: java.lang.reflect.InvocationTargetException
*** Problem's technical details go below ***
Home directory was detected as: /opt/jmeter/apache-jmeter-5.5/lib
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:65)
        at java.base/jdk.internal.platform.Container.metrics(Container.java:43)
        at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(OperatingSystemImpl.java:48)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(PlatformMBeanProviderImpl.java:279)
        at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(PlatformMBeanProviderImpl.java:198)
        at java.management/java.lang.management.ManagementFactory.lambda$getPlatformMBeanServer$0(ManagementFactory.java:487)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1766)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.management/java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:488)
        at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:632)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:55)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
        at org.jmeterplugins.repository.PluginManagerCMD.<clinit>(PluginManagerCMD.java:24)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350)
        at java.base/java.lang.Class.newInstance(Class.java:642)
        at kg.apc.cmdtools.PluginsCMD.getToolInstance(PluginsCMD.java:128)
        at kg.apc.cmdtools.PluginsCMD.processParams(PluginsCMD.java:50)
        at kg.apc.cmdtools.PluginsCMD.processParams(PluginsCMD.java:21)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at kg.apc.cmd.UniversalRunner.main(UniversalRunner.java:117)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at java.base/jdk.internal.platform.Metrics.systemMetrics(Metrics.java:61)
        ... 45 more
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:107)
        at java.base/jdk.internal.platform.CgroupMetrics.getInstance(CgroupMetrics.java:167)
        ... 50 more
Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:260)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at java.base/jdk.internal.platform.CgroupUtil.lambda$readStringValue$1(CgroupUtil.java:66)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
        at java.base/jdk.internal.platform.CgroupUtil.readStringValue(CgroupUtil.java:68)
        at java.base/jdk.internal.platform.CgroupSubsystemController.getStringValue(CgroupSubsystemController.java:65)
        at java.base/jdk.internal.platform.CgroupSubsystemController.getLongValue(CgroupSubsystemController.java:124)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getLongValue(CgroupV1Subsystem.java:272)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.getHierarchical(CgroupV1Subsystem.java:218)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.setPath(CgroupV1Subsystem.java:201)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.setSubSystemControllerPath(CgroupV1Subsystem.java:173)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.lambda$initSubSystem$5(CgroupV1Subsystem.java:113)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.initSubSystem(CgroupV1Subsystem.java:113)
        at java.base/jdk.internal.platform.cgroupv1.CgroupV1Subsystem.<clinit>(CgroupV1Subsystem.java:47)

**Comment by Rbillon59** [comment]
Hello,

When using a fresh clone of the repository and the sample scenario, I'am not encountering the error : 

```
2024-04-16 13:05:49,944 INFO o.j.r.PluginManagerCMD: Command is: install-for-jmx
2024-04-16 13:05:49,980 INFO o.j.r.JARSourceHTTP: Requesting https://jmeter-plugins.org/repo/?installID=linux-d15a808acce96d2fe79f8c90a53b4f2a-nongui
2024-04-16 13:05:51,468 INFO o.j.r.PluginManager: Plugins Status: [jpgc-plugins-manager=plugin-manager, jmeter-core=5.5, jmeter-ftp=5.5, jmeter-http=5.5, jmeter-jdbc=5.5, jmeter-jms=5.5, jmeter-junit=5.5, jmeter-java=5.5, jmeter-ldap=5.5, jmeter-mail=5.5, jmeter-mongodb=5.5, jmeter-native=5.5, jmeter-tcp=5.5, jmeter-components=5.5]
2024-04-16 13:05:51,469 INFO o.j.r.PluginManagerCMD: Params line is: my-scenario.jmx
```

(Using jmeter 5.5 image on both master and slave jobs)

**Comment by Rbillon59** [comment]
Could you describe a bit more your setup ?

Is the ${jmx} variable set with the right jmx ? Does it exists ?

Because 

The error says : 

```
Caused by: java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:208)
at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:260)
at java.base/java.nio.file.Path.of(Path.java:147)
at java.base/java.nio.file.Paths.get(Paths.java:69)
```

It seems like a "no such file or directory"

**Comment by Alireza-Rahimi-3000** [comment]
The error you're encountering seems to be related to the execution of a Java program, specifically involving JMeter's Plugin Manager. Let's break down the error message and try to identify potential causes and solutions.

1. **Primary Error**: 
```
ERROR: java.lang.InternalError: java.lang.reflect.InvocationTargetException
```
   This indicates an internal error in the Java Virtual Machine (JVM), specifically related to a reflective invocation target exception.

2. **Caused by**: 
```
Caused by: java.lang.ExceptionInInitializerError
```
   The exception occurred during the initialization of a class. This is often due to a static initializer block or a static field initializer throwing an exception.

3. **Further Cause**: 
```
Caused by: java.lang.NullPointerException
```
   This suggests a `NullPointerException` occurred within the static initializer block or static field initialization, indicating that some required object reference is null.

The stack trace indicates that the issue might be with the JVM's attempt to access metrics related to the system, potentially through the `CgroupSubsystemFactory`.

Here are some steps you could take to diagnose and potentially resolve the issue:

- **Check Dependencies**: Ensure that all required dependencies for JMeter and its plugins are correctly installed and configured. Sometimes, missing or incompatible dependencies can lead to such runtime errors.

- **Version Compatibility**: Ensure that the versions of Java, JMeter, and any associated plugins are compatible with each other. Mismatched versions can sometimes lead to unexpected errors.

- **Environment Configuration**: Verify that the environment variables and system configurations required by JMeter and its plugins are properly set up. This includes things like `JAVA_HOME` and any other relevant variables.

- **Debugging**: If possible, try to debug the code where the exception is occurring. This might involve inspecting the relevant class (`CgroupSubsystemFactory`, `CgroupMetrics`, etc.) to understand why a `NullPointerException` is being thrown.

- **Consult Documentation**: Check the official documentation for JMeter and its plugins, as well as any relevant forums or communities, to see if others have encountered similar issues and if any solutions or workarounds are available.

By systematically investigating these potential causes and solutions, you should be able to identify and resolve the error you're encountering during the execution of the script involving JMeter's Plugin Manager.

**Comment by Rbillon59** [comment]
@yalem-a To dig up a bit further : 

- What is your CPU arch ?
- Where is your kubernetes hosted ? (cloud, EKS, GKE, AKS, local ?)
- The kubernetes deployment you're using (docker-desktop, k3s, kind, k3d, k0s....)
- Your kubernetes version
- Did you make a change on the scenario or is it a freshly cloned repo ? (Did you add plugins ?)

Because, with my local setup (docker-desktop on Arm64 chip, all is running fine with the sample scenario)

Thank you

**Comment by yalem-a** [comment]
Hello @Rbillon59 ,

I have managed resolving the issue. 

my setup is k8 v1.23 hosted locally within an organization

I have customized the docker image to set the base image as:(that's all i needed to do :) )

`FROM openjdk:23-slim`

I have also set the jmeter version as 5.6.3. 

Roughly speaking the issue was related either of the following as @Alireza-Rahimi-3000 pointed out.

- Old jdk version included in the _openjdk:16-slim_ which is the original base image
-  Latest jmeter plugin-manager is 1.10 as the time of doing this test; which might require latest java version

**Another issue that I needed clarification on:**
I am seeing huge deviations between grafana throughput plots and reports from jtl. I will create a separate issue shorly focused on report dashboards.

Thanks @Rbillon59  for this awesome work you did.

**Comment by Rbillon59** [comment]
Thank you !

I appreciate the feedback and glad you resolved your issue.

Is everything working fine on JDK23 ? (Last year I tried to bump the base image with JDK 21 and I Got issues generating the JMeter reports https://github.com/Rbillon59/jmeter-k8s-base/commit/52bc23d7d85d761d7eef21e2046d05f2610981b2)

**Comment by yalem-a** [comment]
Hello,

The script looks running fine without any issue with openjdk:23.
