### ISSUE TITLE
I reported an error using CSVDate

### ISSUE THREAD

**Issue by tzvine** [Rbillon59/jmeter-k8s-starterkit#39]
2024-09-05 09:32:32,198 INFO o.a.j.r.p.CsvFileSampleSource: produce(): 0 samples produced in 15ms on channel 0
2024-09-05 09:32:32,198 INFO o.a.j.r.d.ReportGenerator: Exporting data using exporter:'json' of className:'org.apache.jmeter.report.dashboard.JsonExporter'
2024-09-05 09:32:32,358 INFO o.a.j.r.d.JsonExporter: Found data for consumer statisticsSummary in context
2024-09-05 09:32:32,358 INFO o.a.j.r.d.JsonExporter: Creating statistics for overall
Error generating the report: java.lang.NullPointerException: Cannot invoke "org.apache.jmeter.report.processor.MapResultData.getResult(String)" because "re
sultData" is null
2024-09-05 09:32:32,359 ERROR o.a.j.JMeter: Error generating the report: Cannot invoke "org.apache.jmeter.report.processor.MapResultData.getResult(String)"
 because "resultData" is null
java.lang.NullPointerException: Cannot invoke "org.apache.jmeter.report.processor.MapResultData.getResult(String)" because "resultData" is null
at org.apache.jmeter.report.dashboard.JsonExporter.createStatistic(JsonExporter.java:121) ~[ApacheJMeter_core.jar:5.4.3]
at org.apache.jmeter.report.dashboard.JsonExporter.export(JsonExporter.java:72) ~[ApacheJMeter_core.jar:5.4.3]
at org.apache.jmeter.report.dashboard.ReportGenerator.exportData(ReportGenerator.java:379) ~[ApacheJMeter_core.jar:5.4.3]
at org.apache.jmeter.report.dashboard.ReportGenerator.generate(ReportGenerator.java:257) ~[ApacheJMeter_core.jar:5.4.3]
at org.apache.jmeter.JMeter$ListenToTest.endTest(JMeter.java:1346) ~[ApacheJMeter_core.jar:5.4.3]
at org.apache.jmeter.JMeter$ListenToTest.lambda$testEnded$0(JMeter.java:1291) ~[ApacheJMeter_core.jar:5.4.3]
at java.lang.Thread.run(Thread.java:831) [?:?]
... end of run

**Comment by Rbillon59** [comment]
Hello,

this issue typically occurs when the result csv is empty. Are you sure the test is running properly ? Did you check on the live reporting on Grafana ?

Could please share your jmx file to ease the investigations ?

Thank you
